version: "3.10"
services:
  angular_app:
    build: 'frontend'
    container_name: angular_app
    ports:
      - "9001:80"
    depends_on:
      - fastapi_app
  fastapi_app:
    build: 'backend'
    container_name: fastapi_app
    ports:
      - "9000:8080"